/**
 * Duck Agent - Self-Improving Learning Loop
 * Hermes-style: skills improve during use, agent nudges itself to remember,
 * builds user model, learns from feedback and outcomes
 */

import { EventEmitter } from 'events';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import Database from 'better-sqlite3';

export interface Interaction {
  id: string;
  sessionId: string;
  input: string;
  output: string;
  outcome: 'success' | 'partial' | 'failed';
  toolsUsed: string[];
  duration: number;
  feedback?: string;
  timestamp: number;
}

export interface LearnedSkill {
  id: string;
  name: string;
  description: string;
  trigger: string;         // what activates this skill
  actions: string[];       // what to do
  successCount: number;
  failureCount: number;
  confidence: number;       // 0-1
  lastUsed: number;
  createdAt: number;
  version: number;
  autoGenerated: boolean;
}

export interface UserModel {
  name: string;
  communicationStyle: 'formal' | 'casual' | 'mixed';
  technicalLevel: 'beginner' | 'intermediate' | 'expert';
  preferences: Record<string, string>;
  dislikes: string[];
  frequentTasks: string[];
  timezone: string;
  language: string;
  lastUpdated: number;
}

export interface KnowledgeNudge {
  id: string;
  type: 'remember' | 'prefer' | 'learn' | 'warn';
  content: string;
  reason: string;
  priority: 'low' | 'medium' | 'high';
  triggeredBy: string;      // what interaction triggered this
  applied: boolean;
  ignored: boolean;
  createdAt: number;
}

export interface SkillImprovement {
  skillId: string;
  improvement: string;
  trigger: string;           // what triggered the improvement
  before: string;
  after: string;
  timestamp: number;
}

export class LearningLoop extends EventEmitter {
  private db: Database.Database;
  private learningDir: string;
  private userModel: UserModel;
  private nudgeCooldown: number = 5 * 60 * 1000; // 5 min between nudges
  private lastNudge: number = 0;
  private interactionCount: number = 0;
  private nudges: KnowledgeNudge[] = [];

  constructor(learningDir?: string) {
    super();
    this.learningDir = learningDir || join(homedir(), '.duck', 'learning');
    mkdirSync(this.learningDir, { recursive: true });
    
    const dbPath = join(this.learningDir, 'learning.db');
    this.db = new Database(dbPath);
    this.db.pragma('journal_mode = WAL');
    
    this.initialize();
    this.userModel = this.loadUserModel();
  }

  private initialize(): void {
    // Interactions
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS interactions (
        id TEXT PRIMARY KEY,
        session_id TEXT NOT NULL,
        input TEXT NOT NULL,
        output TEXT NOT NULL,
        outcome TEXT NOT NULL,
        tools_used TEXT NOT NULL DEFAULT '[]',
        duration INTEGER,
        feedback TEXT,
        timestamp INTEGER NOT NULL
      )
    `);

    // Learned skills
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS learned_skills (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT NOT NULL,
        trigger TEXT NOT NULL,
        actions TEXT NOT NULL DEFAULT '[]',
        success_count INTEGER NOT NULL DEFAULT 0,
        failure_count INTEGER NOT NULL DEFAULT 0,
        confidence REAL NOT NULL DEFAULT 0.5,
        last_used INTEGER NOT NULL DEFAULT 0,
        created_at INTEGER NOT NULL,
        version INTEGER NOT NULL DEFAULT 1,
        auto_generated INTEGER NOT NULL DEFAULT 0
      )
    `);

    // User model
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS user_model (
        id INTEGER PRIMARY KEY CHECK (id = 1),
        name TEXT NOT NULL DEFAULT '',
        communication_style TEXT NOT NULL DEFAULT 'mixed',
        technical_level TEXT NOT NULL DEFAULT 'intermediate',
        preferences TEXT NOT NULL DEFAULT '{}',
        dislikes TEXT NOT NULL DEFAULT '[]',
        frequent_tasks TEXT NOT NULL DEFAULT '[]',
        timezone TEXT NOT NULL DEFAULT 'America/New_York',
        language TEXT NOT NULL DEFAULT 'en',
        last_updated INTEGER NOT NULL
      )
    `);

    // Knowledge nudges
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS nudges (
        id TEXT PRIMARY KEY,
        type TEXT NOT NULL,
        content TEXT NOT NULL,
        reason TEXT NOT NULL,
        priority TEXT NOT NULL DEFAULT 'medium',
        triggered_by TEXT NOT NULL,
        applied INTEGER NOT NULL DEFAULT 0,
        ignored INTEGER NOT NULL DEFAULT 0,
        created_at INTEGER NOT NULL
      )
    `);

    // Skill improvements
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS skill_improvements (
        id TEXT PRIMARY KEY,
        skill_id TEXT NOT NULL,
        improvement TEXT NOT NULL,
        trigger TEXT NOT NULL,
        before TEXT NOT NULL,
        after TEXT NOT NULL,
        timestamp INTEGER NOT NULL
      )
    `);

    // Initialize user_model if empty
    const count = (this.db.prepare(`SELECT COUNT(*) as c FROM user_model`).get() as any).c;
    if (count === 0) {
      this.db.prepare(`INSERT INTO user_model (id, last_updated) VALUES (1, ?)`).run(Date.now());
    }

    // Indexes
    this.db.exec(`
      CREATE INDEX IF NOT EXISTS idx_interaction_session ON interactions(session_id);
      CREATE INDEX IF NOT EXISTS idx_interaction_outcome ON interactions(outcome);
      CREATE INDEX IF NOT EXISTS idx_interaction_timestamp ON interactions(timestamp DESC);
      CREATE INDEX IF NOT EXISTS idx_skills_confidence ON learned_skills(confidence DESC);
      CREATE INDEX IF NOT EXISTS idx_skills_trigger ON learned_skills(trigger);
      CREATE INDEX IF NOT EXISTS idx_nudges_priority ON nudges(priority DESC);
    `);
  }

  // ─── Track Interactions ────────────────────────────────────

  trackInteraction(interaction: Omit<Interaction, 'id'>): string {
    const id = `int_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
    this.interactionCount++;

    // Serialize input/output - SQLite can only bind primitives
    const inputRaw = typeof interaction.input === 'string' ? interaction.input : JSON.stringify(interaction.input);
    const outputRaw = typeof interaction.output === 'string' ? interaction.output : JSON.stringify(interaction.output);
    const inputStr = inputRaw.slice(0, 10000);
    const outputStr = outputRaw.slice(0, 50000);
    console.log('[DEBUG trackInteraction] typeof interaction.input:', typeof interaction.input, 'inputRaw:', String(inputRaw).substring(0, 50));

    this.db.prepare(`
      INSERT INTO interactions (id, session_id, input, output, outcome, tools_used, duration, feedback, timestamp)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      id,
      interaction.sessionId,
      inputStr,
      outputStr,
      interaction.outcome,
      JSON.stringify(interaction.toolsUsed),
      interaction.duration || null,
      interaction.feedback || null,
      interaction.timestamp
    );

    // Create stringified version for downstream functions that expect strings
    const stringifiedInteraction: Interaction = {
      ...interaction,
      id,
      input: inputStr,
      output: outputStr
    };
    console.log('[DEBUG stringify] typeof stringifiedInteraction.input:', typeof stringifiedInteraction.input, 'value:', String(stringifiedInteraction.input).substring(0, 30));

    // Run learning analysis on this interaction
    this.analyzeInteraction(stringifiedInteraction);

    // Maybe nudge
    this.maybeNudge(stringifiedInteraction);

    return id;
  }

  recordFeedback(interactionId: string, feedback: 'positive' | 'negative' | 'correction', text?: string): void {
    this.db.prepare(`UPDATE interactions SET feedback = ? WHERE id = ?`)
      .run(JSON.stringify({ type: feedback, text }), interactionId);

    // Update learned skills based on feedback
    if (feedback === 'positive' || feedback === 'correction') {
      this.updateSkillsFromFeedback(interactionId, feedback, text);
    }

    // Update user model from feedback
    if (text) {
      this.updateUserModelFromFeedback(feedback, text);
    }
  }

  // ─── Learning Analysis ────────────────────────────────────

  private analyzeInteraction(interaction: Interaction): void {
    // DEFENSIVE: Force input to be a string at all costs
    let inputStr: string;
    try {
      if (typeof interaction.input === 'string') {
        inputStr = interaction.input;
      } else if (Array.isArray(interaction.input)) {
        inputStr = JSON.stringify(interaction.input);
      } else if (typeof interaction.input === 'object' && interaction.input !== null) {
        inputStr = JSON.stringify(interaction.input);
      } else {
        inputStr = String(interaction.input);
      }
    } catch {
      inputStr = '[unstringifiable input]';
    }
    let outputStr: string;
    try {
      if (typeof interaction.output === 'string') {
        outputStr = interaction.output;
      } else {
        outputStr = JSON.stringify(interaction.output);
      }
    } catch {
      outputStr = '[unstringifiable output]';
    }
    console.log('[DEBUG analyzeInteraction] inputStr type:', typeof inputStr, 'value:', String(inputStr).substring(0, 30));
    const inputLower = inputStr.toLowerCase();
    const outputLower = outputStr.toLowerCase();

    // Detect complex tasks (multi-step)
    if (interaction.toolsUsed.length > 3 || interaction.duration > 60000) {
      this.maybeCreateLearnedSkill(interaction);
    }

    // Detect repeated patterns
    if (interaction.outcome === 'success') {
      this.updatePatternConfidence(inputLower, outputStr);
    }

    // Detect failures and learn from them
    if (interaction.outcome === 'failed') {
      this.learnFromFailure(interaction);
    }

    // Extract preferences from casual language
    if (inputStr.includes('I prefer') || inputStr.includes('I like') || inputStr.includes("don't like")) {
      this.extractPreference(inputStr);
    }
  }

  private maybeCreateLearnedSkill(interaction: Interaction): void {
    const inputStr = typeof interaction.input === 'string' ? interaction.input : JSON.stringify(interaction.input);
    const outputStr = typeof interaction.output === 'string' ? interaction.output : JSON.stringify(interaction.output);
    const inputLower = inputStr.toLowerCase();
    const outputLower = outputStr.toLowerCase();

    // Check if we already have a similar skill
    const existing = this.db.prepare(`
      SELECT * FROM learned_skills WHERE 
        success_count >= 2 AND
        confidence >= 0.6
      LIMIT 5
    `).all() as any[];

    for (const skill of existing) {
      const triggerWords = skill.trigger.toLowerCase().split(/\s+/);
      const matches = triggerWords.filter((w: string) => inputLower.includes(w)).length;
      if (matches >= 2) {
        // Update this skill's success count
        this.db.prepare(`
          UPDATE learned_skills SET success_count = success_count + 1,
            confidence = LEAST(1.0, (success_count + 1.0) / (success_count + failure_count + 2)),
            last_used = ?
          WHERE id = ?
        `).run(Date.now(), skill.id);
        return;
      }
    }

    // Create a new learned skill if the task was complex and successful
    if (interaction.outcome === 'success' && interaction.toolsUsed.length >= 2) {
      const id = `lskill_${Date.now()}`;
      const trigger = this.extractTriggerPhrase(inputStr);
      const actions = interaction.toolsUsed.slice(0, 5);

      if (trigger && trigger.length > 10) {
        this.db.prepare(`
          INSERT INTO learned_skills (id, name, description, trigger, actions, success_count, confidence, last_used, created_at, auto_generated)
          VALUES (?, ?, ?, ?, ?, 1, 0.6, ?, ?, 1)
        `).run(
          id,
          `Auto: ${trigger.slice(0, 50)}`,
          `Learned from ${interaction.toolsUsed.length} successful interactions`,
          trigger,
          JSON.stringify(actions),
          Date.now(),
          Date.now()
        );
      }
    }
  }

  private extractTriggerPhrase(input: string): string {
    // Extract the key action phrase from the input
    const cleaned = input
      .replace(/[^\w\s]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    // Take the first meaningful phrase (skip common words)
    const skip = ['can', 'you', 'could', 'please', 'help', 'me', 'the', 'a', 'an', 'i', 'want', 'need', 'to', 'how', 'what', 'when', 'where', 'why'];
    const words = cleaned.split(' ').filter((w: string) => w.length > 2 && !skip.includes(w.toLowerCase()));
    
    return words.slice(0, 8).join(' ');
  }

  private updatePatternConfidence(inputPattern: string, output: string): void {
    // Find or create a pattern entry
    const words = inputPattern.split(/\s+/).filter((w: string) => w.length > 4);
    if (words.length === 0) return;

    const keyWord = words[0];
    // This would update existing patterns - simplified here
  }

  private learnFromFailure(interaction: Interaction): void {
    const inputStr = typeof interaction.input === 'string' ? interaction.input : JSON.stringify(interaction.input);
    
    // Create a warning nudge if the same task failed before
    const recentFailures = this.db.prepare(`
      SELECT COUNT(*) as c FROM interactions
      WHERE input LIKE ? AND outcome = 'failed' AND timestamp > ?
    `).get(`%${inputStr.slice(0, 50)}%`, Date.now() - 86400000) as any;

    if (recentFailures.c >= 2) {
      this.createNudge({
        type: 'warn',
        content: `Task "${inputStr.slice(0, 100)}" has failed multiple times. Consider a different approach.`,
        reason: `Failed ${recentFailures.c + 1} times in recent history`,
        priority: 'high',
        triggeredBy: interaction.id
      });
    }
  }

  private extractPreference(input: string): void {
    const preferMatch = input.match(/I prefer ([^.]+)/i);
    const likeMatch = input.match(/I like ([^.]+)/i);
    const dislikeMatch = input.match(/I (?:don't|do not) like ([^.]+)/i);

    if (preferMatch || likeMatch) {
      const pref = (preferMatch ? preferMatch[1] : likeMatch![1]).trim();
      this.updatePreference('likes', pref);
    }

    if (dislikeMatch) {
      const dislike = dislikeMatch[1].trim();
      this.db.prepare(`INSERT INTO user_model (id, last_updated) VALUES (1, ?) ON CONFLICT(id) DO UPDATE SET dislikes = dislikes || ? WHERE id = 1`)
        .run(Date.now(), `,"${dislike}"`);
    }
  }

  // ─── Skill Improvement ──────────────────────────────────────

  private updateSkillsFromFeedback(interactionId: string, feedback: 'positive' | 'negative' | 'correction', text?: string): void {
    // Find the skill that was used for this interaction
    const interaction = this.db.prepare(`SELECT * FROM interactions WHERE id = ?`).get(interactionId) as any;
    if (!interaction) return;

    const toolsUsed = JSON.parse(interaction.tools_used || '[]');
    if (toolsUsed.length === 0) return;

    // Find matching learned skills
    const skills = this.db.prepare(`
      SELECT * FROM learned_skills WHERE auto_generated = 1 LIMIT 3
    `).all() as any[];

    for (const skill of skills) {
      const triggerWords = skill.trigger.toLowerCase().split(/\s+/);
      const inputStr = typeof interaction.input === 'string' ? interaction.input : JSON.stringify(interaction.input);
      const inputLower = inputStr.toLowerCase();
      const matches = triggerWords.filter((w: string) => inputLower.includes(w)).length;

      if (matches >= 2) {
        if (feedback === 'positive') {
          this.db.prepare(`
            UPDATE learned_skills SET
              success_count = success_count + 1,
              confidence = LEAST(1.0, (success_count + 1.0) / (success_count + failure_count + 2)),
              last_used = ?
            WHERE id = ?
          `).run(Date.now(), skill.id);
        } else if (feedback === 'negative') {
          this.db.prepare(`
            UPDATE learned_skills SET
              failure_count = failure_count + 1,
              confidence = GREATEST(0.1, success_count / (success_count + failure_count + 2)),
              last_used = ?
            WHERE id = ?
          `).run(Date.now(), skill.id);

          // Record the improvement
          const improvementId = `imp_${Date.now()}`;
          this.db.prepare(`
            INSERT INTO skill_improvements (id, skill_id, improvement, trigger, before, after, timestamp)
            VALUES (?, ?, ?, ?, ?, ?, ?)
          `).run(
            improvementId,
            skill.id,
            text || 'User gave negative feedback',
            skill.trigger,
            JSON.stringify(toolsUsed),
            JSON.stringify({ feedback, adjustment: 'decreased confidence' }),
            Date.now()
          );
        }
      }
    }
  }

  /**
   * Improve a skill based on a better approach
   */
  improveSkill(skillId: string, improvement: string, trigger: string, before: string, after: string): void {
    const id = `imp_${Date.now()}`;
    this.db.prepare(`
      INSERT INTO skill_improvements (id, skill_id, improvement, trigger, before, after, timestamp)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `).run(id, skillId, improvement, trigger, before, after, Date.now());

    // Update skill version
    this.db.prepare(`
      UPDATE learned_skills SET version = version + 1 WHERE id = ?
    `).run(skillId);
  }

  /**
   * Get the best skill for a task
   */
  getBestSkill(task: string): LearnedSkill | null {
    const taskLower = task.toLowerCase();
    const words = taskLower.split(/\s+/).filter((w: string) => w.length > 3);

    const skills = this.db.prepare(`
      SELECT * FROM learned_skills WHERE confidence >= 0.5
      ORDER BY confidence DESC, success_count DESC
      LIMIT 10
    `).all() as any[];

    let best: any = null;
    let bestScore = 0;

    for (const skill of skills) {
      const skillWords = skill.trigger.toLowerCase().split(/\s+/);
      const score = skillWords.filter((w: string) => words.includes(w)).length;
      
      if (score > bestScore && score >= 2) {
        bestScore = score;
        best = skill;
      }
    }

    if (!best) return null;

    return {
      id: best.id,
      name: best.name,
      description: best.description,
      trigger: best.trigger,
      actions: JSON.parse(best.actions || '[]'),
      successCount: best.success_count,
      failureCount: best.failure_count,
      confidence: best.confidence,
      lastUsed: best.last_used,
      createdAt: best.created_at,
      version: best.version,
      autoGenerated: best.auto_generated === 1
    };
  }

  // ─── Knowledge Nudges ────────────────────────────────────

  private maybeNudge(interaction: Interaction): void {
    if (Date.now() - this.lastNudge < this.nudgeCooldown) return;

    const inputStr = typeof interaction.input === 'string' ? interaction.input : JSON.stringify(interaction.input);
    const inputLower = inputStr.toLowerCase();
    const nudge = this.generateNudge(interaction);

    if (!nudge) return;

    this.createNudge(nudge);
    this.lastNudge = Date.now();

    // Emit for agent to handle
    this.emit('nudge', nudge);
  }

  private generateNudge(interaction: Interaction): Omit<KnowledgeNudge, 'id' | 'createdAt' | 'applied' | 'ignored'> | null {
    const inputStr = typeof interaction.input === 'string' ? interaction.input : JSON.stringify(interaction.input);
    const outputStr = typeof interaction.output === 'string' ? interaction.output : JSON.stringify(interaction.output);
    const inputLower = inputStr.toLowerCase();
    const outputLower = outputStr.toLowerCase();

    // After complex task → suggest remembering
    if (interaction.toolsUsed.length >= 4 && interaction.outcome === 'success') {
      const keyInfo = this.extractKeyOutcome(inputStr, outputStr);
      if (keyInfo) {
        return {
          type: 'remember',
          content: `Remember: ${keyInfo}`,
          reason: 'Complex task completed successfully - save the key outcome',
          priority: 'medium',
          triggeredBy: interaction.id
        };
      }
    }

    // After repeated successful pattern → learn
    if (interaction.outcome === 'success') {
      const pattern = this.detectPattern(inputStr, interaction.sessionId);
      if (pattern && pattern.count >= 3) {
        return {
          type: 'learn',
          content: `Create a skill for: ${pattern.trigger}`,
          reason: `You've done this ${pattern.count} times successfully`,
          priority: 'low',
          triggeredBy: interaction.id
        };
      }
    }

    // User mentions preference → remember it
    if (inputLower.includes('prefer') || inputLower.includes('like') || inputLower.includes('always')) {
      const pref = this.extractPreferencePhrase(inputStr);
      if (pref) {
        return {
          type: 'prefer',
          content: `Remember: ${pref}`,
          reason: 'User stated a preference',
          priority: 'high',
          triggeredBy: interaction.id
        };
      }
    }

    return null;
  }

  private extractKeyOutcome(input: string, output: string): string | null {
    // Simple: find the key result from the output
    // In production, would use LLM to extract
    const lines = output.split('\n').filter(l => l.trim().length > 20);
    if (lines.length > 0) {
      return lines[0].trim().slice(0, 200);
    }
    return null;
  }

  private detectPattern(input: string, sessionId: string): { trigger: string; count: number } | null {
    const words = input.toLowerCase().replace(/[^\w\s]/g, '').split(/\s+/).filter((w: string) => w.length > 4);
    if (words.length < 3) return null;

    const trigger = words.slice(0, 5).join(' ');

    const count = (this.db.prepare(`
      SELECT COUNT(*) as c FROM interactions
      WHERE input LIKE ? AND outcome = 'success' AND timestamp > ?
    `).get(`%${trigger}%`, Date.now() - 7 * 86400000) as any).c;

    if (count >= 3) {
      return { trigger, count };
    }
    return null;
  }

  private extractPreferencePhrase(input: string): string | null {
    const preferMatch = input.match(/I prefer (?:to )?([^.!?]+)/i);
    const likeMatch = input.match(/I like (?:to )?([^.!?]+)/i);
    const alwaysMatch = input.match(/I always ([^.!?]+)/i);

    const phrase = preferMatch?.[1] || likeMatch?.[1] || alwaysMatch?.[1];
    if (phrase) {
      return phrase.trim().slice(0, 200);
    }
    return null;
  }

  private createNudge(nudge: Omit<KnowledgeNudge, 'id' | 'createdAt' | 'applied' | 'ignored'>): void {
    const id = `nudge_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
    const fullNudge: KnowledgeNudge = {
      ...nudge,
      id,
      createdAt: Date.now(),
      applied: false,
      ignored: false
    };

    this.nudges.push(fullNudge);
    if (this.nudges.length > 50) this.nudges.shift();

    this.db.prepare(`
      INSERT INTO nudges (id, type, content, reason, priority, triggered_by, applied, ignored, created_at)
      VALUES (?, ?, ?, ?, ?, ?, 0, 0, ?)
    `).run(id, nudge.type, nudge.content, nudge.reason, nudge.priority, nudge.triggeredBy, Date.now());

    this.emit('nudge', fullNudge);
  }

  getPendingNudges(): KnowledgeNudge[] {
    return this.db.prepare(`
      SELECT * FROM nudges WHERE applied = 0 AND ignored = 0
      ORDER BY 
        CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
        created_at DESC
      LIMIT 10
    `).all() as KnowledgeNudge[];
  }

  applyNudge(nudgeId: string, action: 'apply' | 'ignore'): void {
    this.db.prepare(`UPDATE nudges SET ${action} = 1 WHERE id = ?`).run(nudgeId);
  }

  // ─── User Model ───────────────────────────────────────────

  private loadUserModel(): UserModel {
    const row = this.db.prepare(`SELECT * FROM user_model WHERE id = 1`).get() as any;
    if (!row) {
      return this.defaultUserModel();
    }
    return {
      name: row.name,
      communicationStyle: row.communication_style,
      technicalLevel: row.technical_level,
      preferences: JSON.parse(row.preferences || '{}'),
      dislikes: JSON.parse(row.dislikes || '[]'),
      frequentTasks: JSON.parse(row.frequent_tasks || '[]'),
      timezone: row.timezone,
      language: row.language,
      lastUpdated: row.last_updated
    };
  }

  private defaultUserModel(): UserModel {
    return {
      name: '',
      communicationStyle: 'mixed',
      technicalLevel: 'intermediate',
      preferences: {},
      dislikes: [],
      frequentTasks: [],
      timezone: 'America/New_York',
      language: 'en',
      lastUpdated: Date.now()
    };
  }

  getUserModel(): UserModel {
    return { ...this.userModel };
  }

  updateUserModel(updates: Partial<UserModel>): void {
    const updates2: Record<string, any> = {};
    if (updates.name !== undefined) updates2.name = updates.name;
    if (updates.communicationStyle !== undefined) updates2.communication_style = updates.communicationStyle;
    if (updates.technicalLevel !== undefined) updates2.technical_level = updates.technicalLevel;
    if (updates.preferences !== undefined) updates2.preferences = JSON.stringify(updates.preferences);
    if (updates.dislikes !== undefined) updates2.dislikes = JSON.stringify(updates.dislikes);
    if (updates.frequentTasks !== undefined) updates2.frequent_tasks = JSON.stringify(updates.frequentTasks);
    if (updates.timezone !== undefined) updates2.timezone = updates.timezone;
    if (updates.language !== undefined) updates2.language = updates.language;

    updates2.last_updated = Date.now();

    const setClauses = Object.keys(updates2).map(k => `${k} = ?`).join(', ');
    const values = Object.values(updates2);

    this.db.prepare(`UPDATE user_model SET ${setClauses} WHERE id = 1`).run(...values);

    // Update local model
    Object.assign(this.userModel, updates, { lastUpdated: Date.now() });
  }

  private updatePreference(key: string, value: string): void {
    this.userModel.preferences[key] = value;
    this.db.prepare(`UPDATE user_model SET preferences = ?, last_updated = ? WHERE id = 1`)
      .run(JSON.stringify(this.userModel.preferences), Date.now());
  }

  private updateUserModelFromFeedback(feedback: string, text: string): void {
    const textLower = text.toLowerCase();

    // Detect communication style
    if (textLower.includes('formal') || textLower.includes('professional')) {
      this.updateUserModel({ communicationStyle: 'formal' });
    } else if (textLower.includes('casual') || textLower.includes('chill')) {
      this.updateUserModel({ communicationStyle: 'casual' });
    }

    // Detect technical level
    if (textLower.includes('too technical') || textLower.includes('too complicated') || textLower.includes('simple')) {
      this.updateUserModel({ technicalLevel: 'beginner' });
    } else if (textLower.includes('more detail') || textLower.includes('advanced')) {
      this.updateUserModel({ technicalLevel: 'expert' });
    }
  }

  // ─── Interaction Context ──────────────────────────────────

  /**
   * Get context for a new interaction — recent history, patterns, nudges
   */
  getInteractionContext(sessionId: string, maxInteractions: number = 10): {
    recentInteractions: Interaction[];
    pendingNudges: KnowledgeNudge[];
    learnedSkills: LearnedSkill[];
    userModel: UserModel;
    frequentTasks: { task: string; count: number }[];
  } {
    const recentRows = this.db.prepare(`
      SELECT * FROM interactions WHERE session_id = ?
      ORDER BY timestamp DESC LIMIT ?
    `).all(sessionId, maxInteractions) as any[];

    const recentInteractions: Interaction[] = recentRows.map(r => ({
      id: r.id,
      sessionId: r.session_id,
      input: r.input,
      output: r.output,
      outcome: r.outcome,
      toolsUsed: JSON.parse(r.tools_used || '[]'),
      duration: r.duration,
      feedback: r.feedback,
      timestamp: r.timestamp
    }));

    const nudges = this.getPendingNudges();

    const skillRows = this.db.prepare(`
      SELECT * FROM learned_skills WHERE confidence >= 0.5
      ORDER BY confidence DESC LIMIT 5
    `).all() as any[];

    const learnedSkills: LearnedSkill[] = skillRows.map(r => ({
      id: r.id,
      name: r.name,
      description: r.description,
      trigger: r.trigger,
      actions: JSON.parse(r.actions || '[]'),
      successCount: r.success_count,
      failureCount: r.failure_count,
      confidence: r.confidence,
      lastUsed: r.last_used,
      createdAt: r.created_at,
      version: r.version,
      autoGenerated: r.auto_generated === 1
    }));

    const freqRows = this.db.prepare(`
      SELECT SUBSTR(input, 1, 100) as task, COUNT(*) as count
      FROM interactions WHERE outcome = 'success'
      GROUP BY SUBSTR(input, 1, 100)
      ORDER BY count DESC LIMIT 5
    `).all() as any[];

    const frequentTasks = freqRows.map(r => ({ task: r.task, count: r.count }));

    return {
      recentInteractions,
      pendingNudges: nudges,
      learnedSkills,
      userModel: this.getUserModel(),
      frequentTasks
    };
  }

  /**
   * Build a context prompt from learning loop data
   */
  buildContextPrompt(sessionId: string): string {
    const ctx = this.getInteractionContext(sessionId);
    const parts: string[] = [];

    // Learned skills
    if (ctx.learnedSkills.length > 0) {
      parts.push('## Learned Skills (use when relevant)');
      for (const skill of ctx.learnedSkills) {
        parts.push(`- ${skill.trigger}: ${skill.actions.join(' → ')} (confidence: ${Math.round(skill.confidence * 100)}%)`);
      }
    }

    // Pending nudges
    if (ctx.pendingNudges.length > 0) {
      parts.push('## Pending Reminders');
      for (const nudge of ctx.pendingNudges) {
        if (nudge.priority === 'high' || nudge.priority === 'medium') {
          parts.push(`- [${nudge.type.toUpperCase()}] ${nudge.content} (${nudge.reason})`);
        }
      }
    }

    // Frequent tasks
    if (ctx.frequentTasks.length > 0) {
      parts.push('## Frequent Tasks');
      for (const ft of ctx.frequentTasks.slice(0, 3)) {
        parts.push(`- "${ft.task.slice(0, 60)}" (done ${ft.count}x)`);
      }
    }

    // User preferences
    const prefs = ctx.userModel.preferences;
    const prefKeys = Object.keys(prefs);
    if (prefKeys.length > 0) {
      parts.push('## User Preferences');
      for (const key of prefKeys) {
        parts.push(`- ${key}: ${prefs[key]}`);
      }
    }

    return parts.join('\n');
  }

  // ─── Stats ──────────────────────────────────────────────

  stats(): {
    totalInteractions: number;
    successRate: number;
    learnedSkills: number;
    avgConfidence: number;
    nudgesIssued: number;
    skillVersions: number;
    userModelUpdates: number;
  } {
    const intStats = this.db.prepare(`
      SELECT COUNT(*) as total, 
             SUM(CASE outcome WHEN 'success' THEN 1 ELSE 0 END) as successes
      FROM interactions
    `).get() as any;

    const skillStats = this.db.prepare(`
      SELECT COUNT(*) as count, AVG(confidence) as avg_conf, MAX(version) as max_version
      FROM learned_skills
    `).get() as any;

    const nudgeStats = this.db.prepare(`
      SELECT COUNT(*) as issued FROM nudges
    `).get() as any;

    return {
      totalInteractions: intStats?.total || 0,
      successRate: intStats?.total > 0 ? Math.round((intStats?.successes || 0) / intStats?.total * 100) / 100 : 0,
      learnedSkills: skillStats?.count || 0,
      avgConfidence: Math.round((skillStats?.avg_conf || 0) * 100) / 100,
      nudgesIssued: nudgeStats?.issued || 0,
      skillVersions: skillStats?.max_version || 0,
      userModelUpdates: 0
    };
  }

  close(): void {
    try { if (this.db.open) this.db.close(); } catch {}
  }
}

export default LearningLoop;
