/**
 * Duck Agent - Tool Schema Registry with JSON Schemas
 * MCP-style auto-discovery for all 72 tools
 */

export type ToolCategory = 'android' | 'desktop' | 'system' | 'file' | 'network' | 'ai' | 'memory' | 'browser' | 'coding' | 'planning' | 'cron';

export interface ToolArg { name: string; type: string; description: string; required: boolean; default?: string; }
export interface ToolReturns { type: string; description: string; }
export interface ToolSchema { name: string; description: string; category: ToolCategory; args: ToolArg[]; returns: ToolReturns; errors: string[]; retryable: boolean; fallbackTool?: string; dangerous?: boolean; examples?: string[]; }
const ANDROID_TOOLS: Record<string, ToolSchema> = {
  android_devices: { name: "android_devices", description: "List all connected Android devices via ADB", category: "android", args: [], returns: { type: "AndroidDevice[]", description: "see docs" }, errors: ['ADB not installed', 'No devices connected', 'USB debugging disabled'], retryable: true, examples: ["duck android_devices"], },
  android_refresh: { name: "android_refresh", description: "Refresh the list of connected Android devices", category: "android", args: [], returns: { type: "AndroidDevice[]", description: "see docs" }, errors: ['ADB not available'], retryable: true, examples: ["duck android_refresh"], },
  android_info: { name: "android_info", description: "Get detailed information about an Android device", category: "android", args: [], returns: { type: "DeviceInfo", description: "see docs" }, errors: ['No device selected', 'Device not found', 'ADB error'], retryable: true, examples: ["duck android_info"], },
  android_shell: { name: "android_shell", description: "Execute a shell command on the Android device", category: "android", args: [], returns: { type: "{ stdout: string; stderr: string; exitCode: number }", description: "see docs" }, errors: ['No device selected', 'Command timed out', 'ADB error'], retryable: false, dangerous: true, examples: ["duck android_shell"], },
  android_screenshot: { name: "android_screenshot", description: "Capture the Android device screen as PNG", category: "android", args: [], returns: { type: "ScreenCapture", description: "see docs" }, errors: ['No device selected', 'Screenshot failed', 'Storage error'], retryable: true, examples: ["duck android_screenshot"], },
  android_tap: { name: "android_tap", description: "Tap at screen coordinates (x, y)", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Invalid coordinates', 'Tap failed'], retryable: true, examples: ["duck android_tap"], },
  android_type: { name: "android_type", description: "Type text into the focused field", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'No focused field', 'Type failed'], retryable: true, examples: ["duck android_type"], },
  android_press: { name: "android_press", description: "Press a hardware/key button by name", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Unknown key', 'Press failed'], retryable: true, examples: ["duck android_press"], },
  android_key: { name: "android_key", description: "Press a key by its Android keycode", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Invalid keycode'], retryable: true, dangerous: true, examples: ["duck android_key"], },
  android_dump: { name: "android_dump", description: "Dump the UI hierarchy XML from the current screen", category: "android", args: [], returns: { type: "string", description: "see docs" }, errors: ['No device selected', 'Dump failed'], retryable: true, examples: ["duck android_dump"], },
  android_battery: { name: "android_battery", description: "Get the current battery level percentage", category: "android", args: [], returns: { type: "number", description: "see docs" }, errors: ['No device selected', 'Battery info unavailable'], retryable: true, examples: ["duck android_battery"], },
  android_packages: { name: "android_packages", description: "List all installed packages on the device", category: "android", args: [], returns: { type: "string[]", description: "see docs" }, errors: ['No device selected', 'Package list failed'], retryable: true, examples: ["duck android_packages"], },
  android_launch: { name: "android_launch", description: "Launch an app by package name", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Package not found', 'Launch failed'], retryable: true, examples: ["duck android_launch"], },
  android_kill: { name: "android_kill", description: "Force-stop an app by package name", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Package not found'], retryable: true, examples: ["duck android_kill"], },
  android_install: { name: "android_install", description: "Install an APK on the device", category: "android", args: [], returns: { type: "string", description: "see docs" }, errors: ['No device selected', 'APK not found', 'Install failed', 'Signature mismatch'], retryable: false, dangerous: true, examples: ["duck android_install"], },
  android_uninstall: { name: "android_uninstall", description: "Uninstall a package from the device", category: "android", args: [], returns: { type: "string", description: "see docs" }, errors: ['No device selected', 'Package not found', 'Uninstall failed'], retryable: false, dangerous: true, examples: ["duck android_uninstall"], },
  android_foreground: { name: "android_foreground", description: "Get the currently foreground app package name", category: "android", args: [], returns: { type: "string | null", description: "see docs" }, errors: ['No device selected'], retryable: true, examples: ["duck android_foreground"], },
  android_clipboard: { name: "android_clipboard", description: "Get or set the device clipboard", category: "android", args: [], returns: { type: "string | boolean", description: "see docs" }, errors: ['No device selected', 'Clipboard service unavailable', 'Failed'], retryable: true, examples: ["duck android_clipboard"], },
  android_notifications: { name: "android_notifications", description: "Get recent notifications from the device", category: "android", args: [], returns: { type: "string[]", description: "see docs" }, errors: ['No device selected', 'Notification service unavailable'], retryable: true, examples: ["duck android_notifications"], },
  android_push: { name: "android_push", description: "Push a local file to the device", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Local file not found', 'Push failed'], retryable: true, dangerous: true, examples: ["duck android_push"], },
  android_pull: { name: "android_pull", description: "Pull a file from the device to local", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Remote file not found', 'Pull failed'], retryable: true, examples: ["duck android_pull"], },
  android_swipe: { name: "android_swipe", description: "Perform a swipe gesture", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Invalid coordinates'], retryable: true, examples: ["duck android_swipe"], },
  android_scroll: { name: "android_scroll", description: "Scroll the screen in a direction", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Invalid direction'], retryable: true, examples: ["duck android_scroll"], },
  android_analyze: { name: "android_analyze", description: "Capture screenshot and analyze with vision AI", category: "android", args: [], returns: { type: "ScreenAnalysis", description: "see docs" }, errors: ['No device selected', 'Screenshot failed', 'Vision API unavailable'], retryable: true, examples: ["duck android_analyze"], },
  android_find: { name: "android_find", description: "Find and tap an element by text, content description, or resource ID", category: "android", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No device selected', 'Element not found'], retryable: true, examples: ["duck android_find"], },
  android_termux: { name: "android_termux", description: "Execute a command via Termux API on the device", category: "android", args: [], returns: { type: "string", description: "see docs" }, errors: ['No device selected', 'Termux API not installed', 'Command failed'], retryable: false, examples: ["duck android_termux"], },
  android_screenshot_analyze: { name: "android_screenshot_analyze", description: "Capture screen and get AI analysis of UI elements", category: "android", args: [], returns: { type: "Record<string,unknown>", description: "see docs" }, errors: ['No device selected', 'Capture failed'], retryable: true, examples: ["duck android_screenshot_analyze"], },
  android_reboot: { name: "android_reboot", description: "Reboot the Android device", category: "android", args: [], returns: { type: "string", description: "see docs" }, errors: ['No device selected', 'Reboot failed'], retryable: false, dangerous: true, examples: ["duck android_reboot"], },
};
const DESKTOP_TOOLS: Record<string, ToolSchema> = {
  desktop_open: { name: "desktop_open", description: "Open an application by name or path", category: "desktop", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['App not found', 'Permission denied', 'Open failed'], retryable: true, examples: ["duck desktop_open"], },
  desktop_click: { name: "desktop_click", description: "Click at screen coordinates", category: "desktop", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Invalid coordinates', 'Click failed'], retryable: true, examples: ["duck desktop_click"], },
  desktop_type: { name: "desktop_type", description: "Type text at the current cursor position", category: "desktop", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Type failed', 'No focused field'], retryable: true, examples: ["duck desktop_type"], },
  desktop_screenshot: { name: "desktop_screenshot", description: "Take a screenshot of the desktop", category: "desktop", args: [], returns: { type: "string", description: "see docs" }, errors: ['Screenshot failed', 'Accessibility permission denied'], retryable: true, examples: ["duck desktop_screenshot"], },
};
const SYSTEM_TOOLS: Record<string, ToolSchema> = {
  shell: { name: "shell", description: "Execute a shell command (requires approval)", category: "system", args: [], returns: { type: "{ stdout: string; stderr: string; exitCode: number }", description: "see docs" }, errors: ['Permission denied', 'Command timed out', 'Non-zero exit code', 'Blocked by guard'], retryable: false, dangerous: true, examples: ["duck shell"], },
  exec: { name: "exec", description: "Execute a system command", category: "system", args: [], returns: { type: "{ stdout: string; stderr: string; exitCode: number }", description: "see docs" }, errors: ['Execution failed', 'Timeout', 'Permission denied'], retryable: false, dangerous: true, examples: ["duck exec"], },
  powershell: { name: "powershell", description: "Execute a Windows PowerShell command", category: "system", args: [], returns: { type: "{ stdout: string; stderr: string; exitCode: number }", description: "see docs" }, errors: ['PowerShell not available', 'Command failed', 'Execution policy blocked'], retryable: false, dangerous: true, examples: ["duck powershell"], },
};
const FILE_TOOLS: Record<string, ToolSchema> = {
  file_read: { name: "file_read", description: "Read the contents of a file", category: "file", args: [], returns: { type: "string", description: "see docs" }, errors: ['File not found', 'Permission denied', 'Read error'], retryable: true, examples: ["duck file_read"], },
  file_write: { name: "file_write", description: "Write content to a file", category: "file", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Permission denied', 'Directory not found', 'Write failed'], retryable: true, examples: ["duck file_write"], },
  file_edit: { name: "file_edit", description: "Edit specific text in a file", category: "file", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['File not found', 'oldText not found', 'Edit failed'], retryable: true, examples: ["duck file_edit"], },
  glob: { name: "glob", description: "Find files matching a glob pattern", category: "file", args: [], returns: { type: "string[]", description: "see docs" }, errors: ['Pattern invalid', 'No matches found'], retryable: true, examples: ["duck glob"], },
  grep: { name: "grep", description: "Search for a pattern in files", category: "file", args: [], returns: { type: "string[]", description: "see docs" }, errors: ['Pattern invalid', 'Path not found'], retryable: true, examples: ["duck grep"], },
};
const NETWORK_TOOLS: Record<string, ToolSchema> = {
  web_search: { name: "web_search", description: "Search the web for information", category: "network", args: [], returns: { type: "SearchResult[]", description: "see docs" }, errors: ['Search API unavailable', 'Rate limited', 'No results'], retryable: true, examples: ["duck web_search"], },
  web_fetch: { name: "web_fetch", description: "Fetch and extract readable content from a URL", category: "network", args: [], returns: { type: "string", description: "see docs" }, errors: ['URL unreachable', 'Invalid URL', 'Fetch failed', 'Blocked'], retryable: true, examples: ["duck web_fetch"], },
};
const AI_TOOLS: Record<string, ToolSchema> = {
  think: { name: "think", description: "Use deep reasoning to think through a complex problem", category: "ai", args: [], returns: { type: "string", description: "see docs" }, errors: ['Model unavailable', 'Reasoning failed'], retryable: true, examples: ["duck think"], },
  speak: { name: "speak", description: "Convert text to speech and optionally play audio", category: "ai", args: [], returns: { type: "{ success: boolean; chars: number; file: string }", description: "see docs" }, errors: ['TTS API unavailable', 'Text too long', 'Voice not found'], retryable: true, examples: ["duck speak"], },
  think_and_speak: { name: "think_and_speak", description: "Think deeply then convert the response to speech", category: "ai", args: [], returns: { type: "{ thought: string; audioFile: string }", description: "see docs" }, errors: ['Think failed', 'TTS failed'], retryable: true, examples: ["duck think_and_speak"], },
  image_generate: { name: "image_generate", description: "Generate an image from a text description", category: "ai", args: [], returns: { type: "string", description: "see docs" }, errors: ['Image API unavailable', 'Prompt too long', 'Generation failed'], retryable: true, examples: ["duck image_generate"], },
  vision_analyze: { name: "vision_analyze", description: "Analyze an image using vision AI", category: "ai", args: [], returns: { type: "string", description: "see docs" }, errors: ['Image not found', 'Vision API unavailable', 'Analysis failed'], retryable: true, examples: ["duck vision_analyze"], },
  learn_from_feedback: { name: "learn_from_feedback", description: "Learn from user feedback to improve future responses", category: "ai", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Learning failed', 'Feedback storage error'], retryable: true, examples: ["duck learn_from_feedback"], },
  repl: { name: "repl", description: "Execute code in a REPL environment", category: "ai", args: [], returns: { type: "{ stdout: string; stderr: string; exitCode: number }", description: "see docs" }, errors: ['Language not supported', 'Execution error', 'Timeout'], retryable: true, examples: ["duck repl"], },
  lsp_diagnostics: { name: "lsp_diagnostics", description: "Get code diagnostics from the Language Server Protocol", category: "ai", args: [], returns: { type: "Diagnostic[]", description: "see docs" }, errors: ['LSP unavailable', 'File not found', 'Language not supported'], retryable: true, examples: ["duck lsp_diagnostics"], },
};
const MEMORY_TOOLS: Record<string, ToolSchema> = {
  memory_remember: { name: "memory_remember", description: "Remember information and store it permanently", category: "memory", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Storage failed', 'Memory limit reached'], retryable: true, examples: ["duck memory_remember"], },
  memory_recall: { name: "memory_recall", description: "Search persistent memory for stored information", category: "memory", args: [], returns: { type: "string[]", description: "see docs" }, errors: ['Search failed', 'No memories found'], retryable: true, examples: ["duck memory_recall"], },
  memory_list: { name: "memory_list", description: "List all stored memories", category: "memory", args: [], returns: { type: "MemoryEntry[]", description: "see docs" }, errors: ['Storage error'], retryable: true, examples: ["duck memory_list"], },
  memory_stats: { name: "memory_stats", description: "Show memory system statistics and health", category: "memory", args: [], returns: { type: "MemoryStats", description: "see docs" }, errors: ['Stats unavailable'], retryable: true, examples: ["duck memory_stats"], },
  session_search: { name: "session_search", description: "Search past conversation sessions", category: "memory", args: [], returns: { type: "SessionResult[]", description: "see docs" }, errors: ['Search failed', 'Session store unavailable'], retryable: true, examples: ["duck session_search"], },
  session_list: { name: "session_list", description: "List recent conversation sessions", category: "memory", args: [], returns: { type: "SessionSummary[]", description: "see docs" }, errors: ['Session store unavailable'], retryable: true, examples: ["duck session_list"], },
};
const PLANNING_TOOLS: Record<string, ToolSchema> = {
  plan_create: { name: "plan_create", description: "Create an autonomous plan to achieve a goal", category: "planning", args: [], returns: { type: "Plan", description: "see docs" }, errors: ['Planning failed', 'Goal unclear'], retryable: true, examples: ["duck plan_create"], },
  plan_status: { name: "plan_status", description: "Show the progress of the current plan", category: "planning", args: [], returns: { type: "PlanStatus", description: "see docs" }, errors: ['No active plan'], retryable: true, examples: ["duck plan_status"], },
  plan_list: { name: "plan_list", description: "List all active plans", category: "planning", args: [], returns: { type: "Plan[]", description: "see docs" }, errors: [], retryable: true, examples: ["duck plan_list"], },
  plan_abort: { name: "plan_abort", description: "Abort the current plan", category: "planning", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['No active plan', 'Abort failed'], retryable: true, examples: ["duck plan_abort"], },
};
const CRON_TOOLS: Record<string, ToolSchema> = {
  cron_create: { name: "cron_create", description: "Create a scheduled task from natural language", category: "cron", args: [], returns: { type: "{ id: string; schedule: string }", description: "see docs" }, errors: ['Invalid schedule', 'Creation failed'], retryable: false, examples: ["duck cron_create"], },
  cron_list: { name: "cron_list", description: "List all scheduled cron tasks", category: "cron", args: [], returns: { type: "CronJob[]", description: "see docs" }, errors: [], retryable: false, examples: ["duck cron_list"], },
  cron_enable: { name: "cron_enable", description: "Enable or disable a cron task", category: "cron", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Job not found', 'Update failed'], retryable: false, examples: ["duck cron_enable"], },
  cron_delete: { name: "cron_delete", description: "Delete a cron task", category: "cron", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Job not found', 'Delete failed'], retryable: false, dangerous: true, examples: ["duck cron_delete"], },
  cron_stats: { name: "cron_stats", description: "Show cron scheduler statistics", category: "cron", args: [], returns: { type: "CronStats", description: "see docs" }, errors: [], retryable: false, examples: ["duck cron_stats"], },
};
const BROWSER_TOOLS: Record<string, ToolSchema> = {
  browser_navigate: { name: "browser_navigate", description: "Navigate to a URL in the browser", category: "browser", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Browser unavailable', 'Invalid URL', 'Navigation failed'], retryable: true, examples: ["duck browser_navigate"], },
  browser_click: { name: "browser_click", description: "Click on a page element by reference", category: "browser", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Element not found', 'Click failed'], retryable: true, examples: ["duck browser_click"], },
  browser_type: { name: "browser_type", description: "Type text into a page element", category: "browser", args: [], returns: { type: "boolean", description: "see docs" }, errors: ['Element not found', 'Type failed'], retryable: true, examples: ["duck browser_type"], },
  browser_screenshot: { name: "browser_screenshot", description: "Take a screenshot of the current browser page", category: "browser", args: [], returns: { type: "string", description: "see docs" }, errors: ['Browser unavailable', 'Screenshot failed'], retryable: true, examples: ["duck browser_screenshot"], },
  browser_content: { name: "browser_content", description: "Extract text content from the current page", category: "browser", args: [], returns: { type: "string", description: "see docs" }, errors: ['Browser unavailable', 'Content extraction failed'], retryable: true, examples: ["duck browser_content"], },
};
const METRICS_TOOLS: Record<string, ToolSchema> = {
  get_status: { name: "get_status", description: "Get the current agent status and information", category: "system", args: [], returns: { type: "AgentStatus", description: "see docs" }, errors: [], retryable: true, examples: ["duck get_status"], },
  get_metrics: { name: "get_metrics", description: "Get agent performance metrics", category: "system", args: [], returns: { type: "Metrics", description: "see docs" }, errors: ['Metrics unavailable'], retryable: true, examples: ["duck get_metrics"], },
  get_cost: { name: "get_cost", description: "Get cost tracking information", category: "system", args: [], returns: { type: "CostInfo", description: "see docs" }, errors: [], retryable: true, examples: ["duck get_cost"], },
  delegate_task: { name: "delegate_task", description: "Spawn a subagent to handle a task in parallel", category: "system", args: [], returns: { type: "{ sessionId: string; status: string }", description: "see docs" }, errors: ['Spawn failed', 'Agent unavailable'], retryable: true, dangerous: true, examples: ["duck delegate_task"], },
};
export const ALL_TOOL_SCHEMAS: Record<string, ToolSchema> = { ...ANDROID_TOOLS, ...DESKTOP_TOOLS, ...SYSTEM_TOOLS, ...FILE_TOOLS, ...NETWORK_TOOLS, ...AI_TOOLS, ...MEMORY_TOOLS, ...PLANNING_TOOLS, ...CRON_TOOLS, ...BROWSER_TOOLS, ...METRICS_TOOLS, };
export const TOOL_CATEGORIES: ToolCategory[] = ['android', 'desktop', 'system', 'file', 'network', 'ai', 'memory', 'planning', 'cron', 'browser', 'coding'];
export class SchemaRegistry {
  private schemas: Map<string, ToolSchema> = new Map();
  private categoryIndex: Map<ToolCategory, Set<string>> = new Map();
  constructor() { for (const [name, schema] of Object.entries(ALL_TOOL_SCHEMAS)) { this.schemas.set(name, schema); const cat = schema.category; if (!this.categoryIndex.has(cat)) this.categoryIndex.set(cat, new Set()); this.categoryIndex.get(cat)!.add(name); } }
  get(name: string): ToolSchema | undefined { return this.schemas.get(name); }
  has(name: string): boolean { return this.schemas.has(name); }
  list(): ToolSchema[] { return Array.from(this.schemas.values()); }
  listByCategory(category: ToolCategory): ToolSchema[] { const names = this.categoryIndex.get(category); if (!names) return []; return Array.from(names).map(n => this.schemas.get(n)!).filter(Boolean); }
  search(query: string): ToolSchema[] { const q = query.toLowerCase(); return Array.from(this.schemas.values()).filter(schema => schema.name.toLowerCase().includes(q) || schema.description.toLowerCase().includes(q) || schema.category.toLowerCase().includes(q) || schema.args.some(a => a.name.toLowerCase().includes(q) || a.description.toLowerCase().includes(q))); }
  getMCPTools(): object[] { return this.list().map(schema => ({ name: schema.name, description: schema.description, inputSchema: { type: "object", properties: Object.fromEntries(schema.args.map(arg => [arg.name, { type: arg.type, description: arg.description }])), required: schema.args.filter(a => a.required).map(a => a.name) }, returns: schema.returns, errors: schema.errors, retryable: schema.retryable, dangerous: schema.dangerous || false, fallbackTool: schema.fallbackTool, examples: schema.examples || [] })); }
  count(): number { return this.schemas.size; }
  countByCategory(): Record<ToolCategory, number> { const result: Record<string, number> = {}; for (const [cat, names] of this.categoryIndex) { result[cat] = names.size; } return result as Record<ToolCategory, number>; }
}
export const schemaRegistry = new SchemaRegistry();
export default schemaRegistry;